{
 "title": "Twampy",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Roundtrip Latency and Loss",
   "type": "nodeGraph",
   "description": "Upper values is loss and second value is average latency in ms.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "twampy_latency_avg_edge", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Roundtrip Loss Avg Over All Instances",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "avg(twampy_loss{direction=\"roundtrip\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Roundtrip Latency Avg Over All Instances",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "avg(twampy_latency_min{direction=\"roundtrip\"})",
     "legendFormat": "min"
    },
    {
     "expr": "avg(twampy_latency_max{direction=\"roundtrip\"})",
     "legendFormat": "max"
    },
    {
     "expr": "avg(twampy_latency_avg{direction=\"roundtrip\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Measurement Results",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum_over_time(twampy_result{twampy_result=\"ok\"}[$__range])",
     "legendFormat": "ok"
    },
    {
     "expr": "sum_over_time(twampy_result{twampy_result=\"err\"}[$__range])",
     "legendFormat": "err"
    }
   ]
  },
  {
   "title": "Jitter Avg Over All Instances",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "avg(twampy_jitter{direction=\"roundtrip\"})",
     "legendFormat": " "
    }
   ]
  },
  { "title": "Roundtrip", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Min Roundtrip Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "twampy_latency_min{direction=\"roundtrip\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg Roundtrip Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "twampy_latency_avg{direction=\"roundtrip\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Roundtrip Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "twampy_latency_max{direction=\"roundtrip\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Roundtrip Jitter",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "expr": "twampy_jitter{direction=\"roundtrip\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}