{
 "title": "Twampy",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Roundtrip Latency and Loss",
   "type": "nodeGraph",
   "description": "Upper values is loss and second value is average latency in ms.",
   "gridPos": { "h": 16, "w": 18, "x": 0, "y": 1 },
   "targets": [
    { "expr": "twampy_edge", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Successul Measurements",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(twampy_result_total{result=\"ok\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Measurements",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(twampy_result_total{result=\"err\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Last Unsuccessful Measurements",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(twampy_result_total{result=\"err\"}[$__range]) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Roundtrip", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Min Roundtrip Latency",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "twampy_latency_min{direction=\"roundtrip\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg Roundtrip Latency",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "twampy_latency_avg{direction=\"roundtrip\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Roundtrip Latency",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "twampy_latency_max{direction=\"roundtrip\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Roundtrip Jitter",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "twampy_jitter{direction=\"roundtrip\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}