
{{ if .Values.responder.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "twampy.fullname" . }}-responder
  labels:
    {{- include "twampy.responder.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "twampy.responder.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.responder.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "twampy.responder.labels" . | nindent 8 }}
    {{- with .Values.responder.podLabels }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      {{- if .Values.responder.hostNetwork }}
      hostNetwork: true
      {{ end }}
      {{- with .Values.responder.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.responder.serviceAccount.enabled -}}
      serviceAccountName: {{ include "twampy.responder.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.responder.serviceAccount.automount }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.responder.podSecurityContext | nindent 8 }}
      containers:
        - name: responder
          args: 
          - responder
          {{- range $key, $value := .Values.responder.containerArgs }}
          - --{{ $value }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.responder.securityContext | nindent 12 }}
          image: "{{ .Values.responder.image.repository }}:{{ .Values.responder.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.responder.image.pullPolicy }}
          ports:
            - name: twamp
              containerPort: 20001
              protocol: UDP
          resources:
            {{- toYaml .Values.responder.resources | nindent 12 }}
          {{- with .Values.responder.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.responder.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.responder.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.responder.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.responder.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}