{{- if and .Values.sender.daemonset .Values.sender.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "twampy.fullname" . }}-sender
  labels:
    {{- include "twampy.sender.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "twampy.sender.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.sender.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "twampy.sender.labels" . | nindent 8 }}
    {{- with .Values.sender.podLabels }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      {{- if .Values.responder.hostNetwork }}
      hostNetwork: true
      {{ end }}
      {{- with .Values.sender.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.sender.serviceAccount.enabled -}}
      serviceAccountName: {{ include "twampy.sender.serviceAccountName" . }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.sender.serviceAccount.automount }}
      securityContext:
        {{- toYaml .Values.sender.podSecurityContext | nindent 8 }}
      containers:
        - name: sender
          args: 
          - sender
          {{- if .Values.sender.config.forever }}
          - --forever
          {{-  end }}
          {{- if .Values.sender.config.jsonOutput }}
          - --json
          {{- end }}
          {{- if .Values.sender.config.nodeGraph }}
          - --nodegraph
          {{- end }}
          {{- if .Values.sender.config.metrics }}
          - --metrics
          {{- end }}
          {{- range $key, $value := .Values.sender.containerArgs }}
          - --{{ $value }}
          {{- end }}
          {{- if not (empty .Values.sender.config.responder.address) }}
          - {{ .Values.sender.config.responder.address }}
          {{- else }}
          - {{ include "twampy.fullname" . }}-responder.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.sender.securityContext | nindent 12 }}
          image: "{{ .Values.sender.image.repository }}:{{ .Values.sender.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.sender.image.pullPolicy }}
          {{- if .Values.sender.config.metrics }}
          ports:
            - name: metrics
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: metrics
          readinessProbe:
            httpGet:
              path: /
              port: metrics
          {{- end }}
          resources:
            {{- toYaml .Values.sender.resources | nindent 12 }}
          {{- with .Values.sender.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.sender.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sender.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sender.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sender.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end}}