{{- if .Values.sender.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "twampy.serviceAccountName" . }}
  labels:
    {{- include "twampy.labels" . | nindent 4 }}
  {{- with .Values.sender.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.sender.serviceAccount.automount }}
{{- end }}
